title: Eric Kitagawa
description: Fullstack developer, designer, student
theme_color: white

remote_theme: broccolini/swiss

github_repo: eric-kitagawa.github.io # the GitHub repo name for your project
github_username: eric-kitagawa